### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sodle** [rjhansen/nsrllookup#8]
Using CMake 3.12.1/GCC 7.3.0 on Ubuntu (18.04, 32-bit), upon running `make`, I receive the following error:
```
/home/sodle/nsrllookup/src/query_server.cc:67:65: error: no matching function for call to ‘boost::asio::ip::basic_resolver<boost::asio::ip::tcp>::resolve(std::__cxx11::string&, std::__cxx11::string&)’
         boost::asio::connect(sock, resolver.resolve(SERVER, PORT));
                                                                 ^
```

**Comment by rjhansen** [comment]
Compiles fine on my 18.10 system.  Have you installed the complete Boost development environment?

`$ sudo apt install libboost-dev` should do the trick.

**Comment by sodle** [comment]
Yes, 1.65 is installed.

**Comment by rjhansen** [comment]
[looks at the Boost API]

Ah, there we have it, the particular call I'm using wasn't added to Boost until 1.67.  You have two choices: install Boost 1.67, or give me 24 hours to roll things back to the 1.65 API.  Let me know which you prefer.

**Comment by sodle** [comment]
I should be able to upgrade. Thanks!

**Comment by rjhansen** [comment]
The patch for 1.65 conformance was just applied, FYI.  It was very simple, so no reason not to do it.  :)

**Comment by sodle** [comment]
That error is gone, but more have appeared in its place.

```
/home/sodle/nsrllookup/src/query_server.cc: In function ‘std::set<std::__cxx11::basic_string<char> > query_server(const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/sodle/nsrllookup/src/query_server.cc:60:18: error: ‘io_context’ is not a member of ‘boost::asio’
     boost::asio::io_context iocontext;
                  ^~~~~~~~~~
/home/sodle/nsrllookup/src/query_server.cc:60:18: note: suggested alternative: ‘connect’
     boost::asio::io_context iocontext;
                  ^~~~~~~~~~
                  connect
/home/sodle/nsrllookup/src/query_server.cc:61:30: error: ‘iocontext’ was not declared in this scope
     tcp::resolver resolver { iocontext };
                              ^~~~~~~~~
/home/sodle/nsrllookup/src/query_server.cc:61:30: note: suggested alternative: ‘sigcontext’
     tcp::resolver resolver { iocontext };
                              ^~~~~~~~~
                              sigcontext
/home/sodle/nsrllookup/src/query_server.cc:61:40: error: no matching function for call to ‘boost::asio::ip::basic_resolver<boost::asio::ip::tcp>::basic_resolver(<brace-enclosed initializer list>)’
     tcp::resolver resolver { iocontext };
                                        ^
In file included from /usr/include/boost/asio.hpp:63:0,
                 from /home/sodle/nsrllookup/src/query_server.cc:17:
/usr/include/boost/asio/ip/basic_resolver.hpp:67:12: note: candidate: boost::asio::ip::basic_resolver<InternetProtocol, ResolverService>::basic_resolver(boost::asio::io_service&) [with InternetProtocol = boost::asio::ip::tcp; ResolverService = boost::asio::ip::resolver_service<boost::asio::ip::tcp>]
   explicit basic_resolver(boost::asio::io_service& io_service)
            ^~~~~~~~~~~~~~
/usr/include/boost/asio/ip/basic_resolver.hpp:67:12: note:   conversion of argument 1 would be ill-formed:
/home/sodle/nsrllookup/src/query_server.cc:63:34: error: no matching function for call to ‘boost::asio::basic_stream_socket<boost::asio::ip::tcp>::basic_stream_socket(<brace-enclosed initializer list>)’
     tcp::socket sock { iocontext };
                                  ^
In file included from /usr/include/boost/asio.hpp:31:0,
                 from /home/sodle/nsrllookup/src/query_server.cc:17:
/usr/include/boost/asio/basic_stream_socket.hpp:183:3: note: candidate: template<class Protocol1, class StreamSocketService1> boost::asio::basic_stream_socket<Protocol, StreamSocketService>::basic_stream_socket(boost::asio::basic_stream_socket<Protocol1, StreamSocketService1>&&, typename std::enable_if<std::is_convertible<Protocol1, Protocol>::value>::type*)
   basic_stream_socket(
   ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/asio/basic_stream_socket.hpp:183:3: note:   template argument deduction/substitution failed:
/usr/include/boost/asio/basic_stream_socket.hpp:148:3: note: candidate: boost::asio::basic_stream_socket<Protocol, StreamSocketService>::basic_stream_socket(boost::asio::basic_stream_socket<Protocol, StreamSocketService>&&) [with Protocol = boost::asio::ip::tcp; StreamSocketService = boost::asio::stream_socket_service<boost::asio::ip::tcp>]
   basic_stream_socket(basic_stream_socket&& other)
   ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/asio/basic_stream_socket.hpp:148:3: note:   conversion of argument 1 would be ill-formed:
/usr/include/boost/asio/basic_stream_socket.hpp:130:3: note: candidate: boost::asio::basic_stream_socket<Protocol, StreamSocketService>::basic_stream_socket(boost::asio::io_service&, const protocol_type&, const native_handle_type&) [with Protocol = boost::asio::ip::tcp; StreamSocketService = boost::asio::stream_socket_service<boost::asio::ip::tcp>; boost::asio::basic_stream_socket<Protocol, StreamSocketService>::protocol_type = boost::asio::ip::tcp; boost::asio::basic_stream_socket<Protocol, StreamSocketService>::native_handle_type = int]
   basic_stream_socket(boost::asio::io_service& io_service,
   ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/asio/basic_stream_socket.hpp:130:3: note:   candidate expects 3 arguments, 1 provided
/usr/include/boost/asio/basic_stream_socket.hpp:110:3: note: candidate: boost::asio::basic_stream_socket<Protocol, StreamSocketService>::basic_stream_socket(boost::asio::io_service&, const endpoint_type&) [with Protocol = boost::asio::ip::tcp; StreamSocketService = boost::asio::stream_socket_service<boost::asio::ip::tcp>; boost::asio::basic_stream_socket<Protocol, StreamSocketService>::endpoint_type = boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>]
   basic_stream_socket(boost::asio::io_service& io_service,
   ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/asio/basic_stream_socket.hpp:110:3: note:   candidate expects 2 arguments, 1 provided
/usr/include/boost/asio/basic_stream_socket.hpp:89:3: note: candidate: boost::asio::basic_stream_socket<Protocol, StreamSocketService>::basic_stream_socket(boost::asio::io_service&, const protocol_type&) [with Protocol = boost::asio::ip::tcp; StreamSocketService = boost::asio::stream_socket_service<boost::asio::ip::tcp>; boost::asio::basic_stream_socket<Protocol, StreamSocketService>::protocol_type = boost::asio::ip::tcp]
   basic_stream_socket(boost::asio::io_service& io_service,
   ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/asio/basic_stream_socket.hpp:89:3: note:   candidate expects 2 arguments, 1 provided
/usr/include/boost/asio/basic_stream_socket.hpp:72:12: note: candidate: boost::asio::basic_stream_socket<Protocol, StreamSocketService>::basic_stream_socket(boost::asio::io_service&) [with Protocol = boost::asio::ip::tcp; StreamSocketService = boost::asio::stream_socket_service<boost::asio::ip::tcp>]
   explicit basic_stream_socket(boost::asio::io_service& io_service)
            ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/asio/basic_stream_socket.hpp:72:12: note:   conversion of argument 1 would be ill-formed:
CMakeFiles/nsrllookup.dir/build.make:101: recipe for target 'CMakeFiles/nsrllookup.dir/src/query_server.cc.o' failed
make[2]: *** [CMakeFiles/nsrllookup.dir/src/query_server.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/nsrllookup.dir/all' failed
make[1]: *** [CMakeFiles/nsrllookup.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sodle** [comment]
Thanks for your support with this. If it's easier for you, I can just install Boost 1.67 from source instead.

**Comment by rjhansen** [comment]
Okay, so I have more backporting to do.  :)  I don't mind doing this; just give me a couple of days.

**Comment by sodle** [comment]
No problem. Thanks.

**Comment by rjhansen** [comment]
Should be fixed now -- builds cleanly for me under 18.04.2-LTS.

**Comment by sodle** [comment]
Same - thanks!
